# Generated by Django 6.1 on 2026-09-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Placement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placements',
        ),
    ]
