# Generated by Django 6.1 on 2026-09-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Placement', '0002_delete_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='placements/')),
            ],
        ),
    ]
