# Generated by Django 6.0.7 on 2026-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('educational_qualification', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('training_mode', models.CharField(choices=[('online', 'Live Online'), ('classroom', 'Classroom')], max_length=20)),
                ('location', models.CharField(choices=[('technopark', 'Technopark TVM'), ('thampanoor', 'Thampanoor TVM'), ('kochi', 'Kochi'), ('nagercoil', 'Nagercoil'), ('online', 'Online')], max_length=20)),
                ('preferred_timings', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
