# Generated by Django 6.0.7 on 2026-09-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Courses.courselist'),
        ),
    ]
