# Generated by Django 6.0.7 on 2026-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_studentregistration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='preferred_timings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
