# Generated by Django 6.1 on 2026-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_studentregistration_preferred_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='preferred_timings',
            field=models.JSONField(default=list),
        ),
    ]
