# Generated by Django 6.1 on 2026-09-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_alter_studentregistration_preferred_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
